### ISSUE TITLE
CreateExpiredJob expireIn always is set as 30 days 

### ISSUE THREAD

**Issue by robertgm** [imranmomin/Hangfire.AzureCosmosDb#15] opened 2021-04-20 11:01 UTC
In CosmosDbConnection we have method to create expire job. Last parameter is expireIn. This parameter is always set as 30 days. There is no way to set custom value, for example 1 day or 7 days:
```
public override string CreateExpiredJob(Common.Job job, IDictionary<string, string> parameters, DateTime createdAt, TimeSpan expireIn)
        {
```

**Comment by bzumhagen** [comment] 2021-08-06 16:10
Would also like a fix for this.

**Comment by imranmomin** [comment] 2021-08-06 21:29
@bzumhagen - this method is an override of JobStorageConnection

https://www.github.com/imranmomin/Hangfire.AzureCosmosDb/tree/develop/src%2FCosmosDbConnection.cs

You will need to check how Hangfire itself pass this value. 

Or it could be configuration you need to set while setting up the server

**Comment by bzumhagen** [comment] 2021-08-09 22:03
For anyone else who is looking at this. If you are using

CoreBackgroundJobFactory.Create it ignores your storage setting and defaults to 30 days.

https://github.com/HangfireIO/Hangfire/blob/c23b01061860b4f5b5692e23e8f8cbdbe4681a8b/src/Hangfire.Core/Client/CoreBackgroundJobFactory.cs#L77

**Comment by bzumhagen** [comment] 2021-08-10 20:02
When the background job is enqueued, it is given the 30 day expiration. When the job state is changed, it's supposed to get the configured expiration time.

There is a bug in the cosmos stored procedure to update the jobs, which I have an open PR for here:

https://github.com/imranmomin/Hangfire.AzureCosmosDb/pull/23

**Comment by imranmomin** [comment] 2021-08-10 20:20
Closing this issue as  the pull-request was accepted

**Comment by bzumhagen** [comment] 2021-08-10 20:58
@imranmomin when do you think you'll release?

**Comment by imranmomin** [comment] 2021-08-11 22:54
@bzumhagen - I release a test package. Can you confirm if it works fine

https://www.nuget.org/packages/Hangfire.AzureCosmosDB/1.3.0-develop

`dotnet add package Hangfire.AzureCosmosDB --version 1.3.0-develop`

**Comment by bzumhagen** [comment] 2021-08-12 17:50
@imranmomin  I can confirm that the storedProcedure fix works fine.

However the iStorageConnection.GetJobData still throws when the job is missing. This seems to be because of the way you handle the task, the resulting exception is wrapped in a System.AggregateException instead of just being a Microsoft.Azure.Cosmos.CosmosException.

See https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library

```
 System.AggregateException: One or more errors occurred. (Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: b3e897eb-aa5c-4205-af41-0b2999d53605; Reason: (
Errors : [
  "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
]
);)
 ---> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: b3e897eb-aa5c-4205-af41-0b2999d53605; Reason: (
Errors : [
  "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
]
```

**Closed** 2021-08-19 14:37 UTC
